### ISSUE TITLE
How can I disable log when I cast media to FireTV?

### ISSUE THREAD

**Issue by yuchin067** [ConnectSDK/Connect-SDK-iOS-FireTV#2]
When I cast media to FireTV, the xcode console will print many logs.
But I cast to Roku, there is no such problem.
AMAZONFLING_VERSION is 1.1.2
How can I disable log when I cast media to FireTV?
Thanks.

**Comment by eunikolsky** [comment]
@yuchin067, it is an issue with the Amazon Fling SDK. It is posted here: http://forums.developer.amazon.com/forums/thread.jspa?threadID=8523&tstart=0 You can also leave a comment there.

**Comment by yuchin067** [comment]
I got it.
Thank you for your help.
